pull_request_rules:
  - name: Auto-merge Dependabot updates after required checks pass
    conditions:
      - author=dependabot[bot]
      - base=main
      - check-success=Lint and test
      - check-success=Build Checks
      - check-success=Dependency review
    actions:
      merge:
        method: squash

merge_protections_settings:
  reporting_method: check-runs
